### ISSUE TITLE
Error: Cannot find module 'package.json'

### ISSUE THREAD

**Issue by samualtnorman** [emumud/transpiler#2]
when calling `transpiler.transpileScript`, Node will throw the error `Error: Cannot find module 'package.json'`.

This is because line 5 references a package named `package.json` when really it means to reference the file.
https://github.com/emumud/transpiler/blob/28d84672032517a630836b8a3d8ce33638877df6/index.js#L5

Simply adding `./` before the file name should tell require to look for a file and not a package
```js
const version = require('./package.json').version; ```

**Comment by CanadaHonk** [comment]
Fixed this and another error in latest commit
